FROM ghcr.io/tcarland/tcalibcore:v25.02.01

USER root

ENV TCAMAKE_HOME /opt/tcamake
ENV TCAMAKE_PREFIX /usr
ENV TCAMAKE_PROJECT /opt

RUN mkdir -p /opt/gktrace
COPY . /opt/gktrace

WORKDIR /opt

RUN cd gktrace && \
  source .resources/release.profile && \
  make && \
  make install && \
  make clean

USER tdh
ENTRYPOINT ["/usr/bin/tini", "--"]
