FROM ghcr.io/tcarland/tcalibcore:v26.02.01
ARG RELEASE_VERSION=""

LABEL org.opencontainers.image.authors="Timothy C. Arland <tcarland at gmail.com>" \
      org.opencontainers.image.base.name="ghcr.io/tcarland/tcalibcore:v26.02.001" \
      org.opencontainers.image.description="gktrace Container" \
      org.opencontainers.image.source="https://github.com/tcarland/gktrace" \
      org.opencontainers.image.title="gktrace" \
      org.opencontainers.image.version="${RELEASE_VERSION}"

USER root

ENV TCAMAKE_HOME=/opt/tcamake
ENV TCAMAKE_PREFIX=/usr
ENV TCAMAKE_PROJECT=/opt

COPY . /opt/gktrace

WORKDIR /opt

RUN apt-get -y --no-install-recommends install sudo && \
    chown -R tdh:tdh /opt/gktrace && \
    cd /opt/gktrace && \
    source resources/gktrace-release.env && \
    make && \
    chown -R tdh:tdh /opt/gktrace/gktrace && \
    make install && \
    make clean

USER tdh

ENTRYPOINT ["/usr/bin/tini", "--", "/opt/gktrace/gktrace"]
